from typing import Protocol

from app.models.column_info import ColumnInfo


class DataSource(Protocol):
    def table_exists(self, table_name: str) -> bool: ...
    def get_schema(self, table_name: str) -> list[ColumnInfo]: ...
    def get_row_count(self, table_name: str) -> int: ...
    def get_distinct_count(self, table_name: str, column: str) -> int: ...
    def get_null_count(self, table_name: str, column: str) -> int: ...
    def get_empty_string_count(self, table_name: str, column: str) -> int: ...
    def get_duplicate_key_count(self, table_name: str, primary_key: str) -> int: ...
